### ISSUE TITLE
Add ios support

### ISSUE THREAD

**Issue by Haidar0096** [Haidar0096/fsignalr#2]
Microsoft already created an official client for swift here https://github.com/dotnet/signalr-client-swift/tree/main.

I do not have much experience with swift so if someone has the experience, he must:
-  create the corresponding folders (ios/macos) inside the project (by running `flutter create --template=plugin --platforms=macos,ios`)
- Add the dependency to the library mentioned above, using swift package manager
- Add this line to fsignalr_pigeons.dart:
```
@ConfigurePigeon(
  PigeonOptions(
    dartOut: 'lib/src/pigeons/messages.g.dart',
    javaOut: 'android/src/main/java/com/perfektion/fsignalr/Messages.java',
    javaOptions: JavaOptions(
      package: 'com.perfektion.fsignalr',
      className: 'Messages',
    ),
    swiftOut: 'macos/Classes/Messages.swift', // Add this line
  ),
)
```
- Go to the android folder, see how I created the files in `android/src/main/java/com/perfektion/fsignalr` and create a similar swift file for each java file.
- Add this line to pubspec.yaml
```
  plugin:
    platforms:
      android:
        package: com.perfektion.fsignalr
        pluginClass: FsignalrPlugin
      macos:
        pluginClass: FsignalrPlugin # Add this
```

And I think this should be it.

I already tried doing this but I am getting some linking errors, due to using cocoapods and swift package manager simultaneously I think (I am not experienced in swift).
I think when the linking problem is solved we should be good to go.
